on:
  workflow_call: 
    inputs:
      prID:
        description: 'Pull request node id'
        required: true
        type: string
      args:
        description: 'Arguments for check'
        required: false
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  checkLOC:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: loc
        id: loc
        run: |
          echo "report='$(node ./check.mjs loc ${{ github.event.inputs.args }})'" >> $GITHUB_OUTPUT
      - name: comments
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            mutation($id: ID!, $body: String!) {
              addComment(input: {subjectId: $id, body: $body}) {
                clientMutationId
              }
            }
          variables: |
            id: ${{ github.event.inputs.prID }}
            body: ${{ steps.loc.outputs.report }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: check exceeds
        run: |
          echo "${{ steps.loc.outputs.report }}" | grep -q 'exceeds' && echo 'Error: Limit exceeds' && exit 1