on:
  pull_request: 
    branches:
      - develop
    
permissions:
  contents: read
  pull-requests: write

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo ${{ github.event.pull_request.node_id }}
  checkLOC:
    uses: ./.github/workflows/check.yml
    with:
      prID: ${{ github.event.pull_request.node_id }}
      args: "${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }}"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}