on:
  pull_request: 
    branches:
      - develop
    
permissions:
  pull-requests: write

jobs:
  checkLOC:
    uses: ./.github/workflows/check.yml
    with:
      prID: ${{ github.event.pull_request.node_id }}
      args: "${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }}"