on:
  pull_request: 
    branches:
      - develop

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: loc
        id: loc
        run: echo "report='$(node ./check.mjs loc --report=html-table ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }})'" >> $GITHUB_OUTPUT
      - name: comments
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            mutation($id: String!, $body: String!) {
              addComment(input: {subjectId: $id, body: $body}) {
                clientMutationId
              }
            }
          variables: |
            id: ${{ github.event.pull_request.id }}
            body: ${{ steps.loc.outputs.report }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
