on:
  pull_request: 
    branches:
      - develop

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: loc
        id: loc
        run: echo "report='$(node ./check.mjs loc --report=html-table ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }})'" >> $GITHUB_OUTPUT
      - name: echo
        run: echo "${{ steps.loc.outputs.report }}"
