on:
  pull_request: 
    branches:
      - develop

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: loc
        run: node ./check.mjs loc ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }}